name: ssg-example
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: go-backend
    ports:
      - "8080:${PORT}"
    environment:
      - PORT=${PORT}
      - GOOGLE_BOOK_API_KEY=${GOOGLE_BOOK_API_KEY}
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nuxt-frontend
    ports:
      - "3000:3000"
    environment:
      - NUXT_PUBLIC_API_BASE=http://backend:8080
    restart: unless-stopped
    depends_on:
      - backend
