name: ssg-example
networks:
  app-network:
    name: ssg-example_app-network
    driver: bridge
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: go-backend
    ports:
      - "3010:3010"
    environment:
      PORT: 3010
      GOOGLE_BOOK_API_KEY: ${GOOGLE_BOOK_API_KEY}
      GOCACHE: /root/.cache/go-build
    volumes:
      - ./.cache/go-build:/root/.cache/go-build:ro
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nuxt-frontend
    ports:
      - "4010:4010"
    environment:
      PORT: 4010
      NUXT_PUBLIC_API_BASE: ${NUXT_PUBLIC_API_BASE}
    restart: unless-stopped
    links:
      - "nginx_app:${DOMAIN}"
    networks:
      - app-network
    depends_on:
      - backend
  nginx_app:
    image: nginx:latest
    container_name: nginx_app
    environment:
      DOMAIN: ${DOMAIN}
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/public:/data/public
    ports:
      - 80:80
      - 443:443
    networks:
      - app-network