/* tslint:disable */
/* eslint-disable */
/**
 * ssg-example
 * example backend for static site generation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: koeshiro@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BooksDownloadAccessRestriction
 */
export interface BooksDownloadAccessRestriction {
    /**
     * DeviceAllowed: If restricted, whether access is granted for this (user,
     * device, volume).
     * @type {boolean}
     * @memberof BooksDownloadAccessRestriction
     */
    deviceAllowed?: boolean;
    /**
     * DownloadsAcquired: If restricted, the number of content download licenses
     * already acquired (including the requesting client, if licensed).
     * @type {number}
     * @memberof BooksDownloadAccessRestriction
     */
    downloadsAcquired?: number;
    /**
     * JustAcquired: If deviceAllowed, whether access was just acquired with this
     * request.
     * @type {boolean}
     * @memberof BooksDownloadAccessRestriction
     */
    justAcquired?: boolean;
    /**
     * Kind: Resource type.
     * @type {string}
     * @memberof BooksDownloadAccessRestriction
     */
    kind?: string;
    /**
     * MaxDownloadDevices: If restricted, the maximum number of content download
     * licenses for this volume.
     * @type {number}
     * @memberof BooksDownloadAccessRestriction
     */
    maxDownloadDevices?: number;
    /**
     * Message: Error/warning message.
     * @type {string}
     * @memberof BooksDownloadAccessRestriction
     */
    message?: string;
    /**
     * Nonce: Client nonce for verification. Download access and client-validation
     * only.
     * @type {string}
     * @memberof BooksDownloadAccessRestriction
     */
    nonce?: string;
    /**
     * ReasonCode: Error/warning reason code. Additional codes may be added in the
     * future. 0 OK 100 ACCESS_DENIED_PUBLISHER_LIMIT 101 ACCESS_DENIED_LIMIT 200
     * WARNING_USED_LAST_ACCESS
     * @type {string}
     * @memberof BooksDownloadAccessRestriction
     */
    reasonCode?: string;
    /**
     * Restricted: Whether this volume has any download access restrictions.
     * @type {boolean}
     * @memberof BooksDownloadAccessRestriction
     */
    restricted?: boolean;
    /**
     * Signature: Response signature.
     * @type {string}
     * @memberof BooksDownloadAccessRestriction
     */
    signature?: string;
    /**
     * Source: Client app identifier for verification. Download access and
     * client-validation only.
     * @type {string}
     * @memberof BooksDownloadAccessRestriction
     */
    source?: string;
    /**
     * VolumeId: Identifies the volume for which this entry applies.
     * @type {string}
     * @memberof BooksDownloadAccessRestriction
     */
    volumeId?: string;
}

/**
 * Check if a given object implements the BooksDownloadAccessRestriction interface.
 */
export function instanceOfBooksDownloadAccessRestriction(value: object): value is BooksDownloadAccessRestriction {
    return true;
}

export function BooksDownloadAccessRestrictionFromJSON(json: any): BooksDownloadAccessRestriction {
    return BooksDownloadAccessRestrictionFromJSONTyped(json, false);
}

export function BooksDownloadAccessRestrictionFromJSONTyped(json: any, ignoreDiscriminator: boolean): BooksDownloadAccessRestriction {
    if (json == null) {
        return json;
    }
    return {
        
        'deviceAllowed': json['deviceAllowed'] == null ? undefined : json['deviceAllowed'],
        'downloadsAcquired': json['downloadsAcquired'] == null ? undefined : json['downloadsAcquired'],
        'justAcquired': json['justAcquired'] == null ? undefined : json['justAcquired'],
        'kind': json['kind'] == null ? undefined : json['kind'],
        'maxDownloadDevices': json['maxDownloadDevices'] == null ? undefined : json['maxDownloadDevices'],
        'message': json['message'] == null ? undefined : json['message'],
        'nonce': json['nonce'] == null ? undefined : json['nonce'],
        'reasonCode': json['reasonCode'] == null ? undefined : json['reasonCode'],
        'restricted': json['restricted'] == null ? undefined : json['restricted'],
        'signature': json['signature'] == null ? undefined : json['signature'],
        'source': json['source'] == null ? undefined : json['source'],
        'volumeId': json['volumeId'] == null ? undefined : json['volumeId'],
    };
}

export function BooksDownloadAccessRestrictionToJSON(json: any): BooksDownloadAccessRestriction {
    return BooksDownloadAccessRestrictionToJSONTyped(json, false);
}

export function BooksDownloadAccessRestrictionToJSONTyped(value?: BooksDownloadAccessRestriction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deviceAllowed': value['deviceAllowed'],
        'downloadsAcquired': value['downloadsAcquired'],
        'justAcquired': value['justAcquired'],
        'kind': value['kind'],
        'maxDownloadDevices': value['maxDownloadDevices'],
        'message': value['message'],
        'nonce': value['nonce'],
        'reasonCode': value['reasonCode'],
        'restricted': value['restricted'],
        'signature': value['signature'],
        'source': value['source'],
        'volumeId': value['volumeId'],
    };
}

