/* tslint:disable */
/* eslint-disable */
/**
 * ssg-example
 * example backend for static site generation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: koeshiro@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BooksVolumeVolumeInfoIndustryIdentifiers
 */
export interface BooksVolumeVolumeInfoIndustryIdentifiers {
    /**
     * Identifier: Industry specific volume identifier.
     * @type {string}
     * @memberof BooksVolumeVolumeInfoIndustryIdentifiers
     */
    identifier?: string;
    /**
     * Type: Identifier type. Possible values are ISBN_10, ISBN_13, ISSN and OTHER.
     * @type {string}
     * @memberof BooksVolumeVolumeInfoIndustryIdentifiers
     */
    type?: string;
}

/**
 * Check if a given object implements the BooksVolumeVolumeInfoIndustryIdentifiers interface.
 */
export function instanceOfBooksVolumeVolumeInfoIndustryIdentifiers(value: object): value is BooksVolumeVolumeInfoIndustryIdentifiers {
    return true;
}

export function BooksVolumeVolumeInfoIndustryIdentifiersFromJSON(json: any): BooksVolumeVolumeInfoIndustryIdentifiers {
    return BooksVolumeVolumeInfoIndustryIdentifiersFromJSONTyped(json, false);
}

export function BooksVolumeVolumeInfoIndustryIdentifiersFromJSONTyped(json: any, ignoreDiscriminator: boolean): BooksVolumeVolumeInfoIndustryIdentifiers {
    if (json == null) {
        return json;
    }
    return {
        
        'identifier': json['identifier'] == null ? undefined : json['identifier'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function BooksVolumeVolumeInfoIndustryIdentifiersToJSON(json: any): BooksVolumeVolumeInfoIndustryIdentifiers {
    return BooksVolumeVolumeInfoIndustryIdentifiersToJSONTyped(json, false);
}

export function BooksVolumeVolumeInfoIndustryIdentifiersToJSONTyped(value?: BooksVolumeVolumeInfoIndustryIdentifiers | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'identifier': value['identifier'],
        'type': value['type'],
    };
}

