/* tslint:disable */
/* eslint-disable */
/**
 * ssg-example
 * example backend for static site generation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: koeshiro@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BooksVolumeSaleInfoRetailPrice
 */
export interface BooksVolumeSaleInfoRetailPrice {
    /**
     * Amount: Amount in the currency listed below. (In LITE projection.)
     * @type {number}
     * @memberof BooksVolumeSaleInfoRetailPrice
     */
    amount?: number;
    /**
     * CurrencyCode: An ISO 4217, three-letter currency code. (In LITE projection.)
     * @type {string}
     * @memberof BooksVolumeSaleInfoRetailPrice
     */
    currencyCode?: string;
}

/**
 * Check if a given object implements the BooksVolumeSaleInfoRetailPrice interface.
 */
export function instanceOfBooksVolumeSaleInfoRetailPrice(value: object): value is BooksVolumeSaleInfoRetailPrice {
    return true;
}

export function BooksVolumeSaleInfoRetailPriceFromJSON(json: any): BooksVolumeSaleInfoRetailPrice {
    return BooksVolumeSaleInfoRetailPriceFromJSONTyped(json, false);
}

export function BooksVolumeSaleInfoRetailPriceFromJSONTyped(json: any, ignoreDiscriminator: boolean): BooksVolumeSaleInfoRetailPrice {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'] == null ? undefined : json['amount'],
        'currencyCode': json['currencyCode'] == null ? undefined : json['currencyCode'],
    };
}

export function BooksVolumeSaleInfoRetailPriceToJSON(json: any): BooksVolumeSaleInfoRetailPrice {
    return BooksVolumeSaleInfoRetailPriceToJSONTyped(json, false);
}

export function BooksVolumeSaleInfoRetailPriceToJSONTyped(value?: BooksVolumeSaleInfoRetailPrice | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'currencyCode': value['currencyCode'],
    };
}

