/* tslint:disable */
/* eslint-disable */
/**
 * ssg-example
 * example backend for static site generation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: koeshiro@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BooksVolumeUserInfoUserUploadedVolumeInfo
 */
export interface BooksVolumeUserInfoUserUploadedVolumeInfo {
    /**
     * 
     * @type {string}
     * @memberof BooksVolumeUserInfoUserUploadedVolumeInfo
     */
    processingState?: string;
}

/**
 * Check if a given object implements the BooksVolumeUserInfoUserUploadedVolumeInfo interface.
 */
export function instanceOfBooksVolumeUserInfoUserUploadedVolumeInfo(value: object): value is BooksVolumeUserInfoUserUploadedVolumeInfo {
    return true;
}

export function BooksVolumeUserInfoUserUploadedVolumeInfoFromJSON(json: any): BooksVolumeUserInfoUserUploadedVolumeInfo {
    return BooksVolumeUserInfoUserUploadedVolumeInfoFromJSONTyped(json, false);
}

export function BooksVolumeUserInfoUserUploadedVolumeInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BooksVolumeUserInfoUserUploadedVolumeInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'processingState': json['processingState'] == null ? undefined : json['processingState'],
    };
}

export function BooksVolumeUserInfoUserUploadedVolumeInfoToJSON(json: any): BooksVolumeUserInfoUserUploadedVolumeInfo {
    return BooksVolumeUserInfoUserUploadedVolumeInfoToJSONTyped(json, false);
}

export function BooksVolumeUserInfoUserUploadedVolumeInfoToJSONTyped(value?: BooksVolumeUserInfoUserUploadedVolumeInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'processingState': value['processingState'],
    };
}

