/* tslint:disable */
/* eslint-disable */
/**
 * ssg-example
 * example backend for static site generation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: koeshiro@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BooksVolumeSearchInfo
 */
export interface BooksVolumeSearchInfo {
    /**
     * TextSnippet: A text snippet containing the search query.
     * @type {string}
     * @memberof BooksVolumeSearchInfo
     */
    textSnippet?: string;
}

/**
 * Check if a given object implements the BooksVolumeSearchInfo interface.
 */
export function instanceOfBooksVolumeSearchInfo(value: object): value is BooksVolumeSearchInfo {
    return true;
}

export function BooksVolumeSearchInfoFromJSON(json: any): BooksVolumeSearchInfo {
    return BooksVolumeSearchInfoFromJSONTyped(json, false);
}

export function BooksVolumeSearchInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BooksVolumeSearchInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'textSnippet': json['textSnippet'] == null ? undefined : json['textSnippet'],
    };
}

export function BooksVolumeSearchInfoToJSON(json: any): BooksVolumeSearchInfo {
    return BooksVolumeSearchInfoToJSONTyped(json, false);
}

export function BooksVolumeSearchInfoToJSONTyped(value?: BooksVolumeSearchInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'textSnippet': value['textSnippet'],
    };
}

