/* tslint:disable */
/* eslint-disable */
/**
 * ssg-example
 * example backend for static site generation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: koeshiro@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BooksVolumeVolumeInfoReadingModes
 */
export interface BooksVolumeVolumeInfoReadingModes {
    /**
     * 
     * @type {boolean}
     * @memberof BooksVolumeVolumeInfoReadingModes
     */
    image?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BooksVolumeVolumeInfoReadingModes
     */
    text?: boolean;
}

/**
 * Check if a given object implements the BooksVolumeVolumeInfoReadingModes interface.
 */
export function instanceOfBooksVolumeVolumeInfoReadingModes(value: object): value is BooksVolumeVolumeInfoReadingModes {
    return true;
}

export function BooksVolumeVolumeInfoReadingModesFromJSON(json: any): BooksVolumeVolumeInfoReadingModes {
    return BooksVolumeVolumeInfoReadingModesFromJSONTyped(json, false);
}

export function BooksVolumeVolumeInfoReadingModesFromJSONTyped(json: any, ignoreDiscriminator: boolean): BooksVolumeVolumeInfoReadingModes {
    if (json == null) {
        return json;
    }
    return {
        
        'image': json['image'] == null ? undefined : json['image'],
        'text': json['text'] == null ? undefined : json['text'],
    };
}

export function BooksVolumeVolumeInfoReadingModesToJSON(json: any): BooksVolumeVolumeInfoReadingModes {
    return BooksVolumeVolumeInfoReadingModesToJSONTyped(json, false);
}

export function BooksVolumeVolumeInfoReadingModesToJSONTyped(value?: BooksVolumeVolumeInfoReadingModes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'image': value['image'],
        'text': value['text'],
    };
}

