/* tslint:disable */
/* eslint-disable */
/**
 * ssg-example
 * example backend for static site generation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: koeshiro@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BooksVolumeSaleInfoListPrice
 */
export interface BooksVolumeSaleInfoListPrice {
    /**
     * Amount: Amount in the currency listed below. (In LITE projection.)
     * @type {number}
     * @memberof BooksVolumeSaleInfoListPrice
     */
    amount?: number;
    /**
     * CurrencyCode: An ISO 4217, three-letter currency code. (In LITE projection.)
     * @type {string}
     * @memberof BooksVolumeSaleInfoListPrice
     */
    currencyCode?: string;
}

/**
 * Check if a given object implements the BooksVolumeSaleInfoListPrice interface.
 */
export function instanceOfBooksVolumeSaleInfoListPrice(value: object): value is BooksVolumeSaleInfoListPrice {
    return true;
}

export function BooksVolumeSaleInfoListPriceFromJSON(json: any): BooksVolumeSaleInfoListPrice {
    return BooksVolumeSaleInfoListPriceFromJSONTyped(json, false);
}

export function BooksVolumeSaleInfoListPriceFromJSONTyped(json: any, ignoreDiscriminator: boolean): BooksVolumeSaleInfoListPrice {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'] == null ? undefined : json['amount'],
        'currencyCode': json['currencyCode'] == null ? undefined : json['currencyCode'],
    };
}

export function BooksVolumeSaleInfoListPriceToJSON(json: any): BooksVolumeSaleInfoListPrice {
    return BooksVolumeSaleInfoListPriceToJSONTyped(json, false);
}

export function BooksVolumeSaleInfoListPriceToJSONTyped(value?: BooksVolumeSaleInfoListPrice | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'currencyCode': value['currencyCode'],
    };
}

