/* tslint:disable */
/* eslint-disable */
/**
 * ssg-example
 * example backend for static site generation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: koeshiro@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BooksVolumeUserInfoCopy
 */
export interface BooksVolumeUserInfoCopy {
    /**
     * 
     * @type {number}
     * @memberof BooksVolumeUserInfoCopy
     */
    allowedCharacterCount?: number;
    /**
     * 
     * @type {string}
     * @memberof BooksVolumeUserInfoCopy
     */
    limitType?: string;
    /**
     * 
     * @type {number}
     * @memberof BooksVolumeUserInfoCopy
     */
    remainingCharacterCount?: number;
    /**
     * 
     * @type {string}
     * @memberof BooksVolumeUserInfoCopy
     */
    updated?: string;
}

/**
 * Check if a given object implements the BooksVolumeUserInfoCopy interface.
 */
export function instanceOfBooksVolumeUserInfoCopy(value: object): value is BooksVolumeUserInfoCopy {
    return true;
}

export function BooksVolumeUserInfoCopyFromJSON(json: any): BooksVolumeUserInfoCopy {
    return BooksVolumeUserInfoCopyFromJSONTyped(json, false);
}

export function BooksVolumeUserInfoCopyFromJSONTyped(json: any, ignoreDiscriminator: boolean): BooksVolumeUserInfoCopy {
    if (json == null) {
        return json;
    }
    return {
        
        'allowedCharacterCount': json['allowedCharacterCount'] == null ? undefined : json['allowedCharacterCount'],
        'limitType': json['limitType'] == null ? undefined : json['limitType'],
        'remainingCharacterCount': json['remainingCharacterCount'] == null ? undefined : json['remainingCharacterCount'],
        'updated': json['updated'] == null ? undefined : json['updated'],
    };
}

export function BooksVolumeUserInfoCopyToJSON(json: any): BooksVolumeUserInfoCopy {
    return BooksVolumeUserInfoCopyToJSONTyped(json, false);
}

export function BooksVolumeUserInfoCopyToJSONTyped(value?: BooksVolumeUserInfoCopy | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'allowedCharacterCount': value['allowedCharacterCount'],
        'limitType': value['limitType'],
        'remainingCharacterCount': value['remainingCharacterCount'],
        'updated': value['updated'],
    };
}

