/* tslint:disable */
/* eslint-disable */
/**
 * ssg-example
 * example backend for static site generation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: koeshiro@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BooksReviewAuthor
 */
export interface BooksReviewAuthor {
    /**
     * DisplayName: Name of this person.
     * @type {string}
     * @memberof BooksReviewAuthor
     */
    displayName?: string;
}

/**
 * Check if a given object implements the BooksReviewAuthor interface.
 */
export function instanceOfBooksReviewAuthor(value: object): value is BooksReviewAuthor {
    return true;
}

export function BooksReviewAuthorFromJSON(json: any): BooksReviewAuthor {
    return BooksReviewAuthorFromJSONTyped(json, false);
}

export function BooksReviewAuthorFromJSONTyped(json: any, ignoreDiscriminator: boolean): BooksReviewAuthor {
    if (json == null) {
        return json;
    }
    return {
        
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
    };
}

export function BooksReviewAuthorToJSON(json: any): BooksReviewAuthor {
    return BooksReviewAuthorToJSONTyped(json, false);
}

export function BooksReviewAuthorToJSONTyped(value?: BooksReviewAuthor | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'displayName': value['displayName'],
    };
}

