/* tslint:disable */
/* eslint-disable */
/**
 * ssg-example
 * example backend for static site generation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: koeshiro@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BooksVolumeVolumeInfoDimensions
 */
export interface BooksVolumeVolumeInfoDimensions {
    /**
     * Height: Height or length of this volume (in cm).
     * @type {string}
     * @memberof BooksVolumeVolumeInfoDimensions
     */
    height?: string;
    /**
     * Thickness: Thickness of this volume (in cm).
     * @type {string}
     * @memberof BooksVolumeVolumeInfoDimensions
     */
    thickness?: string;
    /**
     * Width: Width of this volume (in cm).
     * @type {string}
     * @memberof BooksVolumeVolumeInfoDimensions
     */
    width?: string;
}

/**
 * Check if a given object implements the BooksVolumeVolumeInfoDimensions interface.
 */
export function instanceOfBooksVolumeVolumeInfoDimensions(value: object): value is BooksVolumeVolumeInfoDimensions {
    return true;
}

export function BooksVolumeVolumeInfoDimensionsFromJSON(json: any): BooksVolumeVolumeInfoDimensions {
    return BooksVolumeVolumeInfoDimensionsFromJSONTyped(json, false);
}

export function BooksVolumeVolumeInfoDimensionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): BooksVolumeVolumeInfoDimensions {
    if (json == null) {
        return json;
    }
    return {
        
        'height': json['height'] == null ? undefined : json['height'],
        'thickness': json['thickness'] == null ? undefined : json['thickness'],
        'width': json['width'] == null ? undefined : json['width'],
    };
}

export function BooksVolumeVolumeInfoDimensionsToJSON(json: any): BooksVolumeVolumeInfoDimensions {
    return BooksVolumeVolumeInfoDimensionsToJSONTyped(json, false);
}

export function BooksVolumeVolumeInfoDimensionsToJSONTyped(value?: BooksVolumeVolumeInfoDimensions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'height': value['height'],
        'thickness': value['thickness'],
        'width': value['width'],
    };
}

