/* tslint:disable */
/* eslint-disable */
/**
 * ssg-example
 * example backend for static site generation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: koeshiro@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BooksVolumeAccessInfoPdf
 */
export interface BooksVolumeAccessInfoPdf {
    /**
     * AcsTokenLink: URL to retrieve ACS token for pdf download. (In LITE
     * projection.)
     * @type {string}
     * @memberof BooksVolumeAccessInfoPdf
     */
    acsTokenLink?: string;
    /**
     * DownloadLink: URL to download pdf. (In LITE projection.)
     * @type {string}
     * @memberof BooksVolumeAccessInfoPdf
     */
    downloadLink?: string;
    /**
     * IsAvailable: Is a scanned image pdf available either as public domain or for
     * purchase. (In LITE projection.)
     * @type {boolean}
     * @memberof BooksVolumeAccessInfoPdf
     */
    isAvailable?: boolean;
}

/**
 * Check if a given object implements the BooksVolumeAccessInfoPdf interface.
 */
export function instanceOfBooksVolumeAccessInfoPdf(value: object): value is BooksVolumeAccessInfoPdf {
    return true;
}

export function BooksVolumeAccessInfoPdfFromJSON(json: any): BooksVolumeAccessInfoPdf {
    return BooksVolumeAccessInfoPdfFromJSONTyped(json, false);
}

export function BooksVolumeAccessInfoPdfFromJSONTyped(json: any, ignoreDiscriminator: boolean): BooksVolumeAccessInfoPdf {
    if (json == null) {
        return json;
    }
    return {
        
        'acsTokenLink': json['acsTokenLink'] == null ? undefined : json['acsTokenLink'],
        'downloadLink': json['downloadLink'] == null ? undefined : json['downloadLink'],
        'isAvailable': json['isAvailable'] == null ? undefined : json['isAvailable'],
    };
}

export function BooksVolumeAccessInfoPdfToJSON(json: any): BooksVolumeAccessInfoPdf {
    return BooksVolumeAccessInfoPdfToJSONTyped(json, false);
}

export function BooksVolumeAccessInfoPdfToJSONTyped(value?: BooksVolumeAccessInfoPdf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'acsTokenLink': value['acsTokenLink'],
        'downloadLink': value['downloadLink'],
        'isAvailable': value['isAvailable'],
    };
}

