/* tslint:disable */
/* eslint-disable */
/**
 * ssg-example
 * example backend for static site generation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: koeshiro@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BooksVolumeUserInfoFamilySharing
 */
export interface BooksVolumeUserInfoFamilySharing {
    /**
     * FamilyRole: The role of the user in the family.
     * @type {string}
     * @memberof BooksVolumeUserInfoFamilySharing
     */
    familyRole?: string;
    /**
     * IsSharingAllowed: Whether or not this volume can be shared with the family
     * by the user. This includes sharing eligibility of both the volume and the
     * user. If the value is true, the user can initiate a family sharing action.
     * @type {boolean}
     * @memberof BooksVolumeUserInfoFamilySharing
     */
    isSharingAllowed?: boolean;
    /**
     * IsSharingDisabledByFop: Whether or not sharing this volume is temporarily
     * disabled due to issues with the Family Wallet.
     * @type {boolean}
     * @memberof BooksVolumeUserInfoFamilySharing
     */
    isSharingDisabledByFop?: boolean;
}

/**
 * Check if a given object implements the BooksVolumeUserInfoFamilySharing interface.
 */
export function instanceOfBooksVolumeUserInfoFamilySharing(value: object): value is BooksVolumeUserInfoFamilySharing {
    return true;
}

export function BooksVolumeUserInfoFamilySharingFromJSON(json: any): BooksVolumeUserInfoFamilySharing {
    return BooksVolumeUserInfoFamilySharingFromJSONTyped(json, false);
}

export function BooksVolumeUserInfoFamilySharingFromJSONTyped(json: any, ignoreDiscriminator: boolean): BooksVolumeUserInfoFamilySharing {
    if (json == null) {
        return json;
    }
    return {
        
        'familyRole': json['familyRole'] == null ? undefined : json['familyRole'],
        'isSharingAllowed': json['isSharingAllowed'] == null ? undefined : json['isSharingAllowed'],
        'isSharingDisabledByFop': json['isSharingDisabledByFop'] == null ? undefined : json['isSharingDisabledByFop'],
    };
}

export function BooksVolumeUserInfoFamilySharingToJSON(json: any): BooksVolumeUserInfoFamilySharing {
    return BooksVolumeUserInfoFamilySharingToJSONTyped(json, false);
}

export function BooksVolumeUserInfoFamilySharingToJSONTyped(value?: BooksVolumeUserInfoFamilySharing | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'familyRole': value['familyRole'],
        'isSharingAllowed': value['isSharingAllowed'],
        'isSharingDisabledByFop': value['isSharingDisabledByFop'],
    };
}

