/* tslint:disable */
/* eslint-disable */
/**
 * ssg-example
 * example backend for static site generation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: koeshiro@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BooksReviewSource
 */
export interface BooksReviewSource {
    /**
     * Description: Name of the source.
     * @type {string}
     * @memberof BooksReviewSource
     */
    description?: string;
    /**
     * ExtraDescription: Extra text about the source of the review.
     * @type {string}
     * @memberof BooksReviewSource
     */
    extraDescription?: string;
    /**
     * Url: URL of the source of the review.
     * @type {string}
     * @memberof BooksReviewSource
     */
    url?: string;
}

/**
 * Check if a given object implements the BooksReviewSource interface.
 */
export function instanceOfBooksReviewSource(value: object): value is BooksReviewSource {
    return true;
}

export function BooksReviewSourceFromJSON(json: any): BooksReviewSource {
    return BooksReviewSourceFromJSONTyped(json, false);
}

export function BooksReviewSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): BooksReviewSource {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'extraDescription': json['extraDescription'] == null ? undefined : json['extraDescription'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function BooksReviewSourceToJSON(json: any): BooksReviewSource {
    return BooksReviewSourceToJSONTyped(json, false);
}

export function BooksReviewSourceToJSONTyped(value?: BooksReviewSource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'extraDescription': value['extraDescription'],
        'url': value['url'],
    };
}

