/* tslint:disable */
/* eslint-disable */
/**
 * ssg-example
 * example backend for static site generation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: koeshiro@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BooksVolumeSaleInfoOffersRentalDuration
 */
export interface BooksVolumeSaleInfoOffersRentalDuration {
    /**
     * 
     * @type {number}
     * @memberof BooksVolumeSaleInfoOffersRentalDuration
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof BooksVolumeSaleInfoOffersRentalDuration
     */
    unit?: string;
}

/**
 * Check if a given object implements the BooksVolumeSaleInfoOffersRentalDuration interface.
 */
export function instanceOfBooksVolumeSaleInfoOffersRentalDuration(value: object): value is BooksVolumeSaleInfoOffersRentalDuration {
    return true;
}

export function BooksVolumeSaleInfoOffersRentalDurationFromJSON(json: any): BooksVolumeSaleInfoOffersRentalDuration {
    return BooksVolumeSaleInfoOffersRentalDurationFromJSONTyped(json, false);
}

export function BooksVolumeSaleInfoOffersRentalDurationFromJSONTyped(json: any, ignoreDiscriminator: boolean): BooksVolumeSaleInfoOffersRentalDuration {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'unit': json['unit'] == null ? undefined : json['unit'],
    };
}

export function BooksVolumeSaleInfoOffersRentalDurationToJSON(json: any): BooksVolumeSaleInfoOffersRentalDuration {
    return BooksVolumeSaleInfoOffersRentalDurationToJSONTyped(json, false);
}

export function BooksVolumeSaleInfoOffersRentalDurationToJSONTyped(value?: BooksVolumeSaleInfoOffersRentalDuration | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'unit': value['unit'],
    };
}

