/* tslint:disable */
/* eslint-disable */
/**
 * ssg-example
 * example backend for static site generation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: koeshiro@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BooksVolumeLayerInfoLayers } from './BooksVolumeLayerInfoLayers';
import {
    BooksVolumeLayerInfoLayersFromJSON,
    BooksVolumeLayerInfoLayersFromJSONTyped,
    BooksVolumeLayerInfoLayersToJSON,
    BooksVolumeLayerInfoLayersToJSONTyped,
} from './BooksVolumeLayerInfoLayers';

/**
 * 
 * @export
 * @interface BooksVolumeLayerInfo
 */
export interface BooksVolumeLayerInfo {
    /**
     * Layers: A layer should appear here if and only if the layer exists for this
     * book.
     * @type {Array<BooksVolumeLayerInfoLayers>}
     * @memberof BooksVolumeLayerInfo
     */
    layers?: Array<BooksVolumeLayerInfoLayers>;
}

/**
 * Check if a given object implements the BooksVolumeLayerInfo interface.
 */
export function instanceOfBooksVolumeLayerInfo(value: object): value is BooksVolumeLayerInfo {
    return true;
}

export function BooksVolumeLayerInfoFromJSON(json: any): BooksVolumeLayerInfo {
    return BooksVolumeLayerInfoFromJSONTyped(json, false);
}

export function BooksVolumeLayerInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BooksVolumeLayerInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'layers': json['layers'] == null ? undefined : ((json['layers'] as Array<any>).map(BooksVolumeLayerInfoLayersFromJSON)),
    };
}

export function BooksVolumeLayerInfoToJSON(json: any): BooksVolumeLayerInfo {
    return BooksVolumeLayerInfoToJSONTyped(json, false);
}

export function BooksVolumeLayerInfoToJSONTyped(value?: BooksVolumeLayerInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'layers': value['layers'] == null ? undefined : ((value['layers'] as Array<any>).map(BooksVolumeLayerInfoLayersToJSON)),
    };
}

