/* tslint:disable */
/* eslint-disable */
/**
 * ssg-example
 * example backend for static site generation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: koeshiro@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BooksVolumeAccessInfoEpub
 */
export interface BooksVolumeAccessInfoEpub {
    /**
     * AcsTokenLink: URL to retrieve ACS token for epub download. (In LITE
     * projection.)
     * @type {string}
     * @memberof BooksVolumeAccessInfoEpub
     */
    acsTokenLink?: string;
    /**
     * DownloadLink: URL to download epub. (In LITE projection.)
     * @type {string}
     * @memberof BooksVolumeAccessInfoEpub
     */
    downloadLink?: string;
    /**
     * IsAvailable: Is a flowing text epub available either as public domain or for
     * purchase. (In LITE projection.)
     * @type {boolean}
     * @memberof BooksVolumeAccessInfoEpub
     */
    isAvailable?: boolean;
}

/**
 * Check if a given object implements the BooksVolumeAccessInfoEpub interface.
 */
export function instanceOfBooksVolumeAccessInfoEpub(value: object): value is BooksVolumeAccessInfoEpub {
    return true;
}

export function BooksVolumeAccessInfoEpubFromJSON(json: any): BooksVolumeAccessInfoEpub {
    return BooksVolumeAccessInfoEpubFromJSONTyped(json, false);
}

export function BooksVolumeAccessInfoEpubFromJSONTyped(json: any, ignoreDiscriminator: boolean): BooksVolumeAccessInfoEpub {
    if (json == null) {
        return json;
    }
    return {
        
        'acsTokenLink': json['acsTokenLink'] == null ? undefined : json['acsTokenLink'],
        'downloadLink': json['downloadLink'] == null ? undefined : json['downloadLink'],
        'isAvailable': json['isAvailable'] == null ? undefined : json['isAvailable'],
    };
}

export function BooksVolumeAccessInfoEpubToJSON(json: any): BooksVolumeAccessInfoEpub {
    return BooksVolumeAccessInfoEpubToJSONTyped(json, false);
}

export function BooksVolumeAccessInfoEpubToJSONTyped(value?: BooksVolumeAccessInfoEpub | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'acsTokenLink': value['acsTokenLink'],
        'downloadLink': value['downloadLink'],
        'isAvailable': value['isAvailable'],
    };
}

