/* tslint:disable */
/* eslint-disable */
/**
 * ssg-example
 * example backend for static site generation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: koeshiro@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BooksVolumeSaleInfoOffersRetailPrice
 */
export interface BooksVolumeSaleInfoOffersRetailPrice {
    /**
     * 
     * @type {number}
     * @memberof BooksVolumeSaleInfoOffersRetailPrice
     */
    amountInMicros?: number;
    /**
     * 
     * @type {string}
     * @memberof BooksVolumeSaleInfoOffersRetailPrice
     */
    currencyCode?: string;
}

/**
 * Check if a given object implements the BooksVolumeSaleInfoOffersRetailPrice interface.
 */
export function instanceOfBooksVolumeSaleInfoOffersRetailPrice(value: object): value is BooksVolumeSaleInfoOffersRetailPrice {
    return true;
}

export function BooksVolumeSaleInfoOffersRetailPriceFromJSON(json: any): BooksVolumeSaleInfoOffersRetailPrice {
    return BooksVolumeSaleInfoOffersRetailPriceFromJSONTyped(json, false);
}

export function BooksVolumeSaleInfoOffersRetailPriceFromJSONTyped(json: any, ignoreDiscriminator: boolean): BooksVolumeSaleInfoOffersRetailPrice {
    if (json == null) {
        return json;
    }
    return {
        
        'amountInMicros': json['amountInMicros'] == null ? undefined : json['amountInMicros'],
        'currencyCode': json['currencyCode'] == null ? undefined : json['currencyCode'],
    };
}

export function BooksVolumeSaleInfoOffersRetailPriceToJSON(json: any): BooksVolumeSaleInfoOffersRetailPrice {
    return BooksVolumeSaleInfoOffersRetailPriceToJSONTyped(json, false);
}

export function BooksVolumeSaleInfoOffersRetailPriceToJSONTyped(value?: BooksVolumeSaleInfoOffersRetailPrice | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amountInMicros': value['amountInMicros'],
        'currencyCode': value['currencyCode'],
    };
}

