/* tslint:disable */
/* eslint-disable */
/**
 * ssg-example
 * example backend for static site generation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: koeshiro@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BooksVolumeVolumeInfoPanelizationSummary
 */
export interface BooksVolumeVolumeInfoPanelizationSummary {
    /**
     * 
     * @type {boolean}
     * @memberof BooksVolumeVolumeInfoPanelizationSummary
     */
    containsEpubBubbles?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BooksVolumeVolumeInfoPanelizationSummary
     */
    containsImageBubbles?: boolean;
    /**
     * 
     * @type {string}
     * @memberof BooksVolumeVolumeInfoPanelizationSummary
     */
    epubBubbleVersion?: string;
    /**
     * 
     * @type {string}
     * @memberof BooksVolumeVolumeInfoPanelizationSummary
     */
    imageBubbleVersion?: string;
}

/**
 * Check if a given object implements the BooksVolumeVolumeInfoPanelizationSummary interface.
 */
export function instanceOfBooksVolumeVolumeInfoPanelizationSummary(value: object): value is BooksVolumeVolumeInfoPanelizationSummary {
    return true;
}

export function BooksVolumeVolumeInfoPanelizationSummaryFromJSON(json: any): BooksVolumeVolumeInfoPanelizationSummary {
    return BooksVolumeVolumeInfoPanelizationSummaryFromJSONTyped(json, false);
}

export function BooksVolumeVolumeInfoPanelizationSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): BooksVolumeVolumeInfoPanelizationSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'containsEpubBubbles': json['containsEpubBubbles'] == null ? undefined : json['containsEpubBubbles'],
        'containsImageBubbles': json['containsImageBubbles'] == null ? undefined : json['containsImageBubbles'],
        'epubBubbleVersion': json['epubBubbleVersion'] == null ? undefined : json['epubBubbleVersion'],
        'imageBubbleVersion': json['imageBubbleVersion'] == null ? undefined : json['imageBubbleVersion'],
    };
}

export function BooksVolumeVolumeInfoPanelizationSummaryToJSON(json: any): BooksVolumeVolumeInfoPanelizationSummary {
    return BooksVolumeVolumeInfoPanelizationSummaryToJSONTyped(json, false);
}

export function BooksVolumeVolumeInfoPanelizationSummaryToJSONTyped(value?: BooksVolumeVolumeInfoPanelizationSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'containsEpubBubbles': value['containsEpubBubbles'],
        'containsImageBubbles': value['containsImageBubbles'],
        'epubBubbleVersion': value['epubBubbleVersion'],
        'imageBubbleVersion': value['imageBubbleVersion'],
    };
}

