/* tslint:disable */
/* eslint-disable */
/**
 * ssg-example
 * example backend for static site generation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: koeshiro@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BooksVolumeUserInfoRentalPeriod
 */
export interface BooksVolumeUserInfoRentalPeriod {
    /**
     * 
     * @type {string}
     * @memberof BooksVolumeUserInfoRentalPeriod
     */
    endUtcSec?: string;
    /**
     * 
     * @type {string}
     * @memberof BooksVolumeUserInfoRentalPeriod
     */
    startUtcSec?: string;
}

/**
 * Check if a given object implements the BooksVolumeUserInfoRentalPeriod interface.
 */
export function instanceOfBooksVolumeUserInfoRentalPeriod(value: object): value is BooksVolumeUserInfoRentalPeriod {
    return true;
}

export function BooksVolumeUserInfoRentalPeriodFromJSON(json: any): BooksVolumeUserInfoRentalPeriod {
    return BooksVolumeUserInfoRentalPeriodFromJSONTyped(json, false);
}

export function BooksVolumeUserInfoRentalPeriodFromJSONTyped(json: any, ignoreDiscriminator: boolean): BooksVolumeUserInfoRentalPeriod {
    if (json == null) {
        return json;
    }
    return {
        
        'endUtcSec': json['endUtcSec'] == null ? undefined : json['endUtcSec'],
        'startUtcSec': json['startUtcSec'] == null ? undefined : json['startUtcSec'],
    };
}

export function BooksVolumeUserInfoRentalPeriodToJSON(json: any): BooksVolumeUserInfoRentalPeriod {
    return BooksVolumeUserInfoRentalPeriodToJSONTyped(json, false);
}

export function BooksVolumeUserInfoRentalPeriodToJSONTyped(value?: BooksVolumeUserInfoRentalPeriod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'endUtcSec': value['endUtcSec'],
        'startUtcSec': value['startUtcSec'],
    };
}

