/* tslint:disable */
/* eslint-disable */
/**
 * ssg-example
 * example backend for static site generation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: koeshiro@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BooksVolumeLayerInfoLayers
 */
export interface BooksVolumeLayerInfoLayers {
    /**
     * LayerId: The layer id of this layer (e.g. "geo").
     * @type {string}
     * @memberof BooksVolumeLayerInfoLayers
     */
    layerId?: string;
    /**
     * VolumeAnnotationsVersion: The current version of this layer's volume
     * annotations. Note that this version applies only to the data in the
     * books.layers.volumeAnnotations.* responses. The actual annotation data is
     * versioned separately.
     * @type {string}
     * @memberof BooksVolumeLayerInfoLayers
     */
    volumeAnnotationsVersion?: string;
}

/**
 * Check if a given object implements the BooksVolumeLayerInfoLayers interface.
 */
export function instanceOfBooksVolumeLayerInfoLayers(value: object): value is BooksVolumeLayerInfoLayers {
    return true;
}

export function BooksVolumeLayerInfoLayersFromJSON(json: any): BooksVolumeLayerInfoLayers {
    return BooksVolumeLayerInfoLayersFromJSONTyped(json, false);
}

export function BooksVolumeLayerInfoLayersFromJSONTyped(json: any, ignoreDiscriminator: boolean): BooksVolumeLayerInfoLayers {
    if (json == null) {
        return json;
    }
    return {
        
        'layerId': json['layerId'] == null ? undefined : json['layerId'],
        'volumeAnnotationsVersion': json['volumeAnnotationsVersion'] == null ? undefined : json['volumeAnnotationsVersion'],
    };
}

export function BooksVolumeLayerInfoLayersToJSON(json: any): BooksVolumeLayerInfoLayers {
    return BooksVolumeLayerInfoLayersToJSONTyped(json, false);
}

export function BooksVolumeLayerInfoLayersToJSONTyped(value?: BooksVolumeLayerInfoLayers | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'layerId': value['layerId'],
        'volumeAnnotationsVersion': value['volumeAnnotationsVersion'],
    };
}

