/* tslint:disable */
/* eslint-disable */
/**
 * ssg-example
 * example backend for static site generation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: koeshiro@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BooksVolumeSaleInfoOffersListPrice
 */
export interface BooksVolumeSaleInfoOffersListPrice {
    /**
     * 
     * @type {number}
     * @memberof BooksVolumeSaleInfoOffersListPrice
     */
    amountInMicros?: number;
    /**
     * 
     * @type {string}
     * @memberof BooksVolumeSaleInfoOffersListPrice
     */
    currencyCode?: string;
}

/**
 * Check if a given object implements the BooksVolumeSaleInfoOffersListPrice interface.
 */
export function instanceOfBooksVolumeSaleInfoOffersListPrice(value: object): value is BooksVolumeSaleInfoOffersListPrice {
    return true;
}

export function BooksVolumeSaleInfoOffersListPriceFromJSON(json: any): BooksVolumeSaleInfoOffersListPrice {
    return BooksVolumeSaleInfoOffersListPriceFromJSONTyped(json, false);
}

export function BooksVolumeSaleInfoOffersListPriceFromJSONTyped(json: any, ignoreDiscriminator: boolean): BooksVolumeSaleInfoOffersListPrice {
    if (json == null) {
        return json;
    }
    return {
        
        'amountInMicros': json['amountInMicros'] == null ? undefined : json['amountInMicros'],
        'currencyCode': json['currencyCode'] == null ? undefined : json['currencyCode'],
    };
}

export function BooksVolumeSaleInfoOffersListPriceToJSON(json: any): BooksVolumeSaleInfoOffersListPrice {
    return BooksVolumeSaleInfoOffersListPriceToJSONTyped(json, false);
}

export function BooksVolumeSaleInfoOffersListPriceToJSONTyped(value?: BooksVolumeSaleInfoOffersListPrice | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amountInMicros': value['amountInMicros'],
        'currencyCode': value['currencyCode'],
    };
}

