/* tslint:disable */
/* eslint-disable */
/**
 * ssg-example
 * example backend for static site generation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: koeshiro@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BooksVolumeSaleInfoOffersRentalDuration } from './BooksVolumeSaleInfoOffersRentalDuration';
import {
    BooksVolumeSaleInfoOffersRentalDurationFromJSON,
    BooksVolumeSaleInfoOffersRentalDurationFromJSONTyped,
    BooksVolumeSaleInfoOffersRentalDurationToJSON,
    BooksVolumeSaleInfoOffersRentalDurationToJSONTyped,
} from './BooksVolumeSaleInfoOffersRentalDuration';
import type { BooksVolumeSaleInfoOffersRetailPrice } from './BooksVolumeSaleInfoOffersRetailPrice';
import {
    BooksVolumeSaleInfoOffersRetailPriceFromJSON,
    BooksVolumeSaleInfoOffersRetailPriceFromJSONTyped,
    BooksVolumeSaleInfoOffersRetailPriceToJSON,
    BooksVolumeSaleInfoOffersRetailPriceToJSONTyped,
} from './BooksVolumeSaleInfoOffersRetailPrice';
import type { BooksVolumeSaleInfoOffersListPrice } from './BooksVolumeSaleInfoOffersListPrice';
import {
    BooksVolumeSaleInfoOffersListPriceFromJSON,
    BooksVolumeSaleInfoOffersListPriceFromJSONTyped,
    BooksVolumeSaleInfoOffersListPriceToJSON,
    BooksVolumeSaleInfoOffersListPriceToJSONTyped,
} from './BooksVolumeSaleInfoOffersListPrice';

/**
 * 
 * @export
 * @interface BooksVolumeSaleInfoOffers
 */
export interface BooksVolumeSaleInfoOffers {
    /**
     * FinskyOfferType: The finsky offer type (e.g., PURCHASE=0 RENTAL=3)
     * @type {number}
     * @memberof BooksVolumeSaleInfoOffers
     */
    finskyOfferType?: number;
    /**
     * Giftable: Indicates whether the offer is giftable.
     * @type {boolean}
     * @memberof BooksVolumeSaleInfoOffers
     */
    giftable?: boolean;
    /**
     * ListPrice: Offer list (=undiscounted) price in Micros.
     * @type {BooksVolumeSaleInfoOffersListPrice}
     * @memberof BooksVolumeSaleInfoOffers
     */
    listPrice?: BooksVolumeSaleInfoOffersListPrice;
    /**
     * RentalDuration: The rental duration (for rental offers only).
     * @type {BooksVolumeSaleInfoOffersRentalDuration}
     * @memberof BooksVolumeSaleInfoOffers
     */
    rentalDuration?: BooksVolumeSaleInfoOffersRentalDuration;
    /**
     * RetailPrice: Offer retail (=discounted) price in Micros
     * @type {BooksVolumeSaleInfoOffersRetailPrice}
     * @memberof BooksVolumeSaleInfoOffers
     */
    retailPrice?: BooksVolumeSaleInfoOffersRetailPrice;
}

/**
 * Check if a given object implements the BooksVolumeSaleInfoOffers interface.
 */
export function instanceOfBooksVolumeSaleInfoOffers(value: object): value is BooksVolumeSaleInfoOffers {
    return true;
}

export function BooksVolumeSaleInfoOffersFromJSON(json: any): BooksVolumeSaleInfoOffers {
    return BooksVolumeSaleInfoOffersFromJSONTyped(json, false);
}

export function BooksVolumeSaleInfoOffersFromJSONTyped(json: any, ignoreDiscriminator: boolean): BooksVolumeSaleInfoOffers {
    if (json == null) {
        return json;
    }
    return {
        
        'finskyOfferType': json['finskyOfferType'] == null ? undefined : json['finskyOfferType'],
        'giftable': json['giftable'] == null ? undefined : json['giftable'],
        'listPrice': json['listPrice'] == null ? undefined : BooksVolumeSaleInfoOffersListPriceFromJSON(json['listPrice']),
        'rentalDuration': json['rentalDuration'] == null ? undefined : BooksVolumeSaleInfoOffersRentalDurationFromJSON(json['rentalDuration']),
        'retailPrice': json['retailPrice'] == null ? undefined : BooksVolumeSaleInfoOffersRetailPriceFromJSON(json['retailPrice']),
    };
}

export function BooksVolumeSaleInfoOffersToJSON(json: any): BooksVolumeSaleInfoOffers {
    return BooksVolumeSaleInfoOffersToJSONTyped(json, false);
}

export function BooksVolumeSaleInfoOffersToJSONTyped(value?: BooksVolumeSaleInfoOffers | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'finskyOfferType': value['finskyOfferType'],
        'giftable': value['giftable'],
        'listPrice': BooksVolumeSaleInfoOffersListPriceToJSON(value['listPrice']),
        'rentalDuration': BooksVolumeSaleInfoOffersRentalDurationToJSON(value['rentalDuration']),
        'retailPrice': BooksVolumeSaleInfoOffersRetailPriceToJSON(value['retailPrice']),
    };
}

