/* tslint:disable */
/* eslint-disable */
/**
 * ssg-example
 * example backend for static site generation
 *
 * The version of the OpenAPI document: 1.0
 * Contact: koeshiro@yandex.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BooksVolumeseriesinfoVolumeSeriesIssue
 */
export interface BooksVolumeseriesinfoVolumeSeriesIssue {
    /**
     * 
     * @type {string}
     * @memberof BooksVolumeseriesinfoVolumeSeriesIssue
     */
    issueDisplayNumber?: string;
    /**
     * 
     * @type {number}
     * @memberof BooksVolumeseriesinfoVolumeSeriesIssue
     */
    issueOrderNumber?: number;
}

/**
 * Check if a given object implements the BooksVolumeseriesinfoVolumeSeriesIssue interface.
 */
export function instanceOfBooksVolumeseriesinfoVolumeSeriesIssue(value: object): value is BooksVolumeseriesinfoVolumeSeriesIssue {
    return true;
}

export function BooksVolumeseriesinfoVolumeSeriesIssueFromJSON(json: any): BooksVolumeseriesinfoVolumeSeriesIssue {
    return BooksVolumeseriesinfoVolumeSeriesIssueFromJSONTyped(json, false);
}

export function BooksVolumeseriesinfoVolumeSeriesIssueFromJSONTyped(json: any, ignoreDiscriminator: boolean): BooksVolumeseriesinfoVolumeSeriesIssue {
    if (json == null) {
        return json;
    }
    return {
        
        'issueDisplayNumber': json['issueDisplayNumber'] == null ? undefined : json['issueDisplayNumber'],
        'issueOrderNumber': json['issueOrderNumber'] == null ? undefined : json['issueOrderNumber'],
    };
}

export function BooksVolumeseriesinfoVolumeSeriesIssueToJSON(json: any): BooksVolumeseriesinfoVolumeSeriesIssue {
    return BooksVolumeseriesinfoVolumeSeriesIssueToJSONTyped(json, false);
}

export function BooksVolumeseriesinfoVolumeSeriesIssueToJSONTyped(value?: BooksVolumeseriesinfoVolumeSeriesIssue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'issueDisplayNumber': value['issueDisplayNumber'],
        'issueOrderNumber': value['issueOrderNumber'],
    };
}

